export const VIDEO_RANDOM_VID_REQUEST = 'VIDEO_RANDOM_VID_REQUEST';
export const VIDEO_RANDOM_VID_SUCCESS = 'VIDEO_RANDOM_VID_SUCCESS';
export const VIDEO_RANDOM_VID_EMPTY = 'VIDEO_RANDOM_VID_EMPTY';
export const VIDEO_RANDOM_VID_FAIL = 'VIDEO_RANDOM_VID_FAIL';
export const VIDEO_PLAY_NEXT_VIDEO = 'VIDEO_PLAY_NEXT_VIDEO';

export const VIDEO_SEARCHED_VID_REQUEST = 'VIDEO_SEARCHED_VID_REQUEST';
export const VIDEO_SEARCHED_VID_SUCCESS = 'VIDEO_SEARCHED_VID_SUCCESS';
export const VIDEO_SEARCHED_VID_EMPTY = 'VIDEO_SEARCHED_VID_EMPTY';
export const VIDEO_SEARCHED_VID_FAIL = 'VIDEO_SEARCHED_VID_FAIL';

